# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindows.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1304, 611)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMouseTracking(True)
        MainWindow.setToolTipDuration(0)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.BN_4 = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BN_4.sizePolicy().hasHeightForWidth())
        self.BN_4.setSizePolicy(sizePolicy)
        self.BN_4.setObjectName("BN_4")
        self.gridLayout.addWidget(self.BN_4, 1, 5, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(166, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(167, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 6, 1, 1)
        self.BN_2 = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BN_2.sizePolicy().hasHeightForWidth())
        self.BN_2.setSizePolicy(sizePolicy)
        self.BN_2.setObjectName("BN_2")
        self.gridLayout.addWidget(self.BN_2, 1, 3, 1, 1)
        self.BN_3 = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BN_3.sizePolicy().hasHeightForWidth())
        self.BN_3.setSizePolicy(sizePolicy)
        self.BN_3.setObjectName("BN_3")
        self.gridLayout.addWidget(self.BN_3, 1, 4, 1, 1)
        self.label_R = QtWidgets.QLabel(self.centralWidget)
        self.label_R.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_R.sizePolicy().hasHeightForWidth())
        self.label_R.setSizePolicy(sizePolicy)
        self.label_R.setMinimumSize(QtCore.QSize(640, 512))
        self.label_R.setObjectName("label_R")
        self.gridLayout.addWidget(self.label_R, 2, 4, 1, 3)
        self.label_L = QtWidgets.QLabel(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_L.sizePolicy().hasHeightForWidth())
        self.label_L.setSizePolicy(sizePolicy)
        self.label_L.setMinimumSize(QtCore.QSize(640, 512))
        self.label_L.setTextFormat(QtCore.Qt.AutoText)
        self.label_L.setObjectName("label_L")
        self.gridLayout.addWidget(self.label_L, 2, 0, 1, 4)
        self.BN_1 = QtWidgets.QPushButton(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.BN_1.sizePolicy().hasHeightForWidth())
        self.BN_1.setSizePolicy(sizePolicy)
        self.BN_1.setObjectName("BN_1")
        self.gridLayout.addWidget(self.BN_1, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setEnabled(True)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1304, 28))
        self.menuBar.setObjectName("menuBar")
        self.menufile_F = QtWidgets.QMenu(self.menuBar)
        self.menufile_F.setGeometry(QtCore.QRect(306, 147, 160, 175))
        self.menufile_F.setObjectName("menufile_F")
        self.menutensorRT = QtWidgets.QMenu(self.menufile_F)
        self.menutensorRT.setObjectName("menutensorRT")
        self.menuhelp = QtWidgets.QMenu(self.menuBar)
        self.menuhelp.setGeometry(QtCore.QRect(386, 147, 158, 175))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menuhelp.sizePolicy().hasHeightForWidth())
        self.menuhelp.setSizePolicy(sizePolicy)
        self.menuhelp.setAutoFillBackground(False)
        self.menuhelp.setObjectName("menuhelp")
        self.menuhelp_2 = QtWidgets.QMenu(self.menuBar)
        self.menuhelp_2.setObjectName("menuhelp_2")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.statusBar.sizePolicy().hasHeightForWidth())
        self.statusBar.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(173, 127, 168))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(173, 127, 168))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(190, 190, 190))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.statusBar.setPalette(palette)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.action_darknet = QtWidgets.QAction(MainWindow)
        self.action_darknet.setCheckable(True)
        self.action_darknet.setChecked(True)
        self.action_darknet.setIconVisibleInMenu(True)
        self.action_darknet.setObjectName("action_darknet")
        self.action_other = QtWidgets.QAction(MainWindow)
        self.action_other.setCheckable(True)
        self.action_other.setObjectName("action_other")
        self.action_Exit_Q = QtWidgets.QAction(MainWindow)
        self.action_Exit_Q.setObjectName("action_Exit_Q")
        self.action_pic = QtWidgets.QAction(MainWindow)
        self.action_pic.setCheckable(True)
        self.action_pic.setChecked(False)
        self.action_pic.setEnabled(True)
        self.action_pic.setIconVisibleInMenu(False)
        self.action_pic.setObjectName("action_pic")
        self.action_video = QtWidgets.QAction(MainWindow)
        self.action_video.setCheckable(True)
        self.action_video.setObjectName("action_video")
        self.action_txt = QtWidgets.QAction(MainWindow)
        self.action_txt.setCheckable(True)
        self.action_txt.setObjectName("action_txt")
        self.action_folder = QtWidgets.QAction(MainWindow)
        self.action_folder.setCheckable(True)
        self.action_folder.setObjectName("action_folder")
        self.action_camera = QtWidgets.QAction(MainWindow)
        self.action_camera.setCheckable(True)
        self.action_camera.setChecked(True)
        self.action_camera.setObjectName("action_camera")
        self.action_Reset = QtWidgets.QAction(MainWindow)
        self.action_Reset.setObjectName("action_Reset")
        self.action_yolov3_rt = QtWidgets.QAction(MainWindow)
        self.action_yolov3_rt.setCheckable(True)
        self.action_yolov3_rt.setObjectName("action_yolov3_rt")
        self.action_yolov4_rt = QtWidgets.QAction(MainWindow)
        self.action_yolov4_rt.setCheckable(True)
        self.action_yolov4_rt.setObjectName("action_yolov4_rt")
        self.action_yolov5_rt = QtWidgets.QAction(MainWindow)
        self.action_yolov5_rt.setCheckable(True)
        self.action_yolov5_rt.setObjectName("action_yolov5_rt")
        self.actioncopr_right = QtWidgets.QAction(MainWindow)
        self.actioncopr_right.setObjectName("actioncopr_right")
        self.menutensorRT.addAction(self.action_yolov3_rt)
        self.menutensorRT.addAction(self.action_yolov4_rt)
        self.menutensorRT.addAction(self.action_yolov5_rt)
        self.menufile_F.addAction(self.action_darknet)
        self.menufile_F.addAction(self.menutensorRT.menuAction())
        self.menufile_F.addAction(self.action_other)
        self.menufile_F.addAction(self.action_Reset)
        self.menufile_F.addAction(self.action_Exit_Q)
        self.menuhelp.addAction(self.action_pic)
        self.menuhelp.addAction(self.action_video)
        self.menuhelp.addAction(self.action_txt)
        self.menuhelp.addAction(self.action_folder)
        self.menuhelp.addAction(self.action_camera)
        self.menuhelp_2.addAction(self.actioncopr_right)
        self.menuBar.addAction(self.menufile_F.menuAction())
        self.menuBar.addAction(self.menuhelp.menuAction())
        self.menuBar.addAction(self.menuhelp_2.menuAction())

        self.retranslateUi(MainWindow)
        self.action_Exit_Q.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BN_4.setText(_translate("MainWindow", "stop"))
        self.BN_2.setText(_translate("MainWindow", "Imshow"))
        self.BN_3.setText(_translate("MainWindow", "Detect"))
        self.label_R.setText(_translate("MainWindow", "DETECTION"))
        self.label_L.setText(_translate("MainWindow", "VIEW"))
        self.BN_1.setText(_translate("MainWindow", "stop"))
        self.menufile_F.setTitle(_translate("MainWindow", "Model(M)"))
        self.menutensorRT.setTitle(_translate("MainWindow", "TensorRT"))
        self.menuhelp.setTitle(_translate("MainWindow", "Source(S)"))
        self.menuhelp_2.setTitle(_translate("MainWindow", "Help"))
        self.action_darknet.setText(_translate("MainWindow", "Darknet"))
        self.action_other.setText(_translate("MainWindow", "Other"))
        self.action_Exit_Q.setText(_translate("MainWindow", "Exit(Q)"))
        self.action_pic.setText(_translate("MainWindow", "Pic"))
        self.action_video.setText(_translate("MainWindow", "Video"))
        self.action_txt.setText(_translate("MainWindow", "Txt"))
        self.action_folder.setText(_translate("MainWindow", "Folder"))
        self.action_camera.setText(_translate("MainWindow", "Camera"))
        self.action_Reset.setText(_translate("MainWindow", "Reset"))
        self.action_yolov3_rt.setText(_translate("MainWindow", "YoloV3"))
        self.action_yolov4_rt.setText(_translate("MainWindow", "YoloV4"))
        self.action_yolov5_rt.setText(_translate("MainWindow", "YoloV5"))
        self.actioncopr_right.setText(_translate("MainWindow", "Copy@Right"))

import names_rc
